//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace consultarCliente.wsCliente {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsClienteSoap", Namespace="http://tempuri.org/")]
    public partial class wsCliente : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback buscarClientePorNombreOperationCompleted;
        
        private System.Threading.SendOrPostCallback mostrarTodosOperationCompleted;
        
        private System.Threading.SendOrPostCallback guardarClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback eliminarClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback modificarClienteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wsCliente() {
            this.Url = global::consultarCliente.Properties.Settings.Default.consultarCliente_wsCliente_wsCliente;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event buscarClientePorNombreCompletedEventHandler buscarClientePorNombreCompleted;
        
        /// <remarks/>
        public event mostrarTodosCompletedEventHandler mostrarTodosCompleted;
        
        /// <remarks/>
        public event guardarClienteCompletedEventHandler guardarClienteCompleted;
        
        /// <remarks/>
        public event eliminarClienteCompletedEventHandler eliminarClienteCompleted;
        
        /// <remarks/>
        public event modificarClienteCompletedEventHandler modificarClienteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarClientePorNombre", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet buscarClientePorNombre(string nombre1) {
            object[] results = this.Invoke("buscarClientePorNombre", new object[] {
                        nombre1});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void buscarClientePorNombreAsync(string nombre1) {
            this.buscarClientePorNombreAsync(nombre1, null);
        }
        
        /// <remarks/>
        public void buscarClientePorNombreAsync(string nombre1, object userState) {
            if ((this.buscarClientePorNombreOperationCompleted == null)) {
                this.buscarClientePorNombreOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarClientePorNombreOperationCompleted);
            }
            this.InvokeAsync("buscarClientePorNombre", new object[] {
                        nombre1}, this.buscarClientePorNombreOperationCompleted, userState);
        }
        
        private void OnbuscarClientePorNombreOperationCompleted(object arg) {
            if ((this.buscarClientePorNombreCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarClientePorNombreCompleted(this, new buscarClientePorNombreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mostrarTodos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet mostrarTodos(string nombre) {
            object[] results = this.Invoke("mostrarTodos", new object[] {
                        nombre});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void mostrarTodosAsync(string nombre) {
            this.mostrarTodosAsync(nombre, null);
        }
        
        /// <remarks/>
        public void mostrarTodosAsync(string nombre, object userState) {
            if ((this.mostrarTodosOperationCompleted == null)) {
                this.mostrarTodosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmostrarTodosOperationCompleted);
            }
            this.InvokeAsync("mostrarTodos", new object[] {
                        nombre}, this.mostrarTodosOperationCompleted, userState);
        }
        
        private void OnmostrarTodosOperationCompleted(object arg) {
            if ((this.mostrarTodosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mostrarTodosCompleted(this, new mostrarTodosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/guardarCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet guardarCliente(string nombre1, string paterno, string materno, string fecha, string correo, string telefono, string sexo) {
            object[] results = this.Invoke("guardarCliente", new object[] {
                        nombre1,
                        paterno,
                        materno,
                        fecha,
                        correo,
                        telefono,
                        sexo});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void guardarClienteAsync(string nombre1, string paterno, string materno, string fecha, string correo, string telefono, string sexo) {
            this.guardarClienteAsync(nombre1, paterno, materno, fecha, correo, telefono, sexo, null);
        }
        
        /// <remarks/>
        public void guardarClienteAsync(string nombre1, string paterno, string materno, string fecha, string correo, string telefono, string sexo, object userState) {
            if ((this.guardarClienteOperationCompleted == null)) {
                this.guardarClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnguardarClienteOperationCompleted);
            }
            this.InvokeAsync("guardarCliente", new object[] {
                        nombre1,
                        paterno,
                        materno,
                        fecha,
                        correo,
                        telefono,
                        sexo}, this.guardarClienteOperationCompleted, userState);
        }
        
        private void OnguardarClienteOperationCompleted(object arg) {
            if ((this.guardarClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.guardarClienteCompleted(this, new guardarClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/eliminarCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet eliminarCliente(string id) {
            object[] results = this.Invoke("eliminarCliente", new object[] {
                        id});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void eliminarClienteAsync(string id) {
            this.eliminarClienteAsync(id, null);
        }
        
        /// <remarks/>
        public void eliminarClienteAsync(string id, object userState) {
            if ((this.eliminarClienteOperationCompleted == null)) {
                this.eliminarClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OneliminarClienteOperationCompleted);
            }
            this.InvokeAsync("eliminarCliente", new object[] {
                        id}, this.eliminarClienteOperationCompleted, userState);
        }
        
        private void OneliminarClienteOperationCompleted(object arg) {
            if ((this.eliminarClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.eliminarClienteCompleted(this, new eliminarClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/modificarCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet modificarCliente(string id, string nombre1, string paterno, string materno, string fecha, string correo, string telefono, string sexo) {
            object[] results = this.Invoke("modificarCliente", new object[] {
                        id,
                        nombre1,
                        paterno,
                        materno,
                        fecha,
                        correo,
                        telefono,
                        sexo});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void modificarClienteAsync(string id, string nombre1, string paterno, string materno, string fecha, string correo, string telefono, string sexo) {
            this.modificarClienteAsync(id, nombre1, paterno, materno, fecha, correo, telefono, sexo, null);
        }
        
        /// <remarks/>
        public void modificarClienteAsync(string id, string nombre1, string paterno, string materno, string fecha, string correo, string telefono, string sexo, object userState) {
            if ((this.modificarClienteOperationCompleted == null)) {
                this.modificarClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmodificarClienteOperationCompleted);
            }
            this.InvokeAsync("modificarCliente", new object[] {
                        id,
                        nombre1,
                        paterno,
                        materno,
                        fecha,
                        correo,
                        telefono,
                        sexo}, this.modificarClienteOperationCompleted, userState);
        }
        
        private void OnmodificarClienteOperationCompleted(object arg) {
            if ((this.modificarClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.modificarClienteCompleted(this, new modificarClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void buscarClientePorNombreCompletedEventHandler(object sender, buscarClientePorNombreCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarClientePorNombreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarClientePorNombreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void mostrarTodosCompletedEventHandler(object sender, mostrarTodosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mostrarTodosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mostrarTodosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void guardarClienteCompletedEventHandler(object sender, guardarClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class guardarClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal guardarClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void eliminarClienteCompletedEventHandler(object sender, eliminarClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class eliminarClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal eliminarClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void modificarClienteCompletedEventHandler(object sender, modificarClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class modificarClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal modificarClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591